language: python

python:
  - "3.6"		#Set pyhton version

install:
  - pip3 install -r requirements.txt		#Install dependencies

before_script:
  - python3 src/AsyncService.py & 		#Launch service for testing
  - sleep 5s

script:
  - python3 -m pytest tests/test_data.py 		#Running tests
